"""
schema.py — Pydantic models for the intelligence object.
Every component of the pipeline produces one of these typed objects.
Validation happens automatically — no silent bad data.
"""
from __future__ import annotations
from datetime import datetime
from typing import Literal, Optional
from pydantic import BaseModel, Field


Signal = Literal["BULLISH", "BEARISH", "NEUTRAL"]


class NewsSentimentSignal(BaseModel):
    score: float = Field(..., ge=-1.0, le=1.0, description="Sentiment score -1 to 1")
    label: Signal
    articles_analyzed: int = Field(..., ge=0)
    top_headlines: list[str] = Field(default_factory=list, max_length=5)
    sources: list[str] = Field(default_factory=list)


class HiringTrendSignal(BaseModel):
    jobs_30d: int = Field(..., ge=0)
    top_departments: list[str] = Field(default_factory=list)
    yoy_change_pct: Optional[float] = None
    signal: Signal
    data_available: bool = True


class FilingLanguageSignal(BaseModel):
    guidance_tone: Literal["positive", "neutral", "negative", "unavailable"]
    risk_factor_delta: Optional[int] = None   # change in number of risk factors vs last filing
    key_phrases: list[str] = Field(default_factory=list)
    filing_date: Optional[str] = None
    signal: Signal


class PricingSignal(BaseModel):
    price_changes_30d: int = Field(default=0, ge=0)
    competitor_changes: int = Field(default=0, ge=0)
    geo_price_gap: Optional[float] = None    # % difference between US and EU pricing if detected
    signal: Signal


class Signals(BaseModel):
    news_sentiment: NewsSentimentSignal
    hiring_trend: HiringTrendSignal
    filing_language: FilingLanguageSignal
    pricing: PricingSignal


class SignalDrift(BaseModel):
    """Captures a change in signal between two consecutive pipeline runs."""
    previous_signal:     Signal
    previous_confidence: int
    direction: Literal["improved", "deteriorated", "reversed", "confidence_shift"]
    explanation: str
    detected_at: str


class IntelligenceObject(BaseModel):
    """
    The core output of the MarketPulse pipeline.
    One object per company, generated by the full ingestion + synthesis loop.
    """
    ticker: str
    company: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    confidence: int = Field(..., ge=0, le=100, description="0-100 confidence score")
    composite_signal: Signal
    signals: Signals
    key_risks: list[str] = Field(default_factory=list)
    recommended_action: str = ""
    pipeline_version: str = "1.0.0"
    data_sources_used: list[str] = Field(default_factory=list)
    drift: Optional[SignalDrift] = None

    def to_api_dict(self) -> dict:
        """Serialise for the REST API response."""
        d = self.model_dump()
        d["generated_at"] = self.generated_at.isoformat() + "Z"
        return d

    @property
    def is_fresh(self) -> bool:
        """True if the object was generated within the last hour."""
        from config import CACHE_TTL
        age = (datetime.utcnow() - self.generated_at).total_seconds()
        return age < CACHE_TTL


class ValidationResult(BaseModel):
    """Output of the data quality validator."""
    ticker: str
    passed: bool
    warnings: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
